"""
dedupe.py

Generates a stable article_id from a URL, so that re-scraping the same
article (e.g. running fetch_news.py again the next day and getting the
same article back in the API response) produces the same ID and gets
skipped by upsert_articles() instead of duplicated.

The URL is hashed rather than using the source's own ID (if any) because
not all sources provide one, and URLs are a reasonably reliable unique
identifier for a specific piece of content. This greatly lowers the chance
of duplicate IDs being generated by accident.
"""

import hashlib

def make_article_id(url: str) -> str:
    """
    Returns a stable, deterministic hash of a URL to use as article_id.

    Same URL in -> same ID out, every time. That's the property that
    makes upsert-based deduplication work.
    """
    normalized = url.strip().lower()
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()